image: javiersantos/android-ci:28.0.3

before_script:
  # temporarily disable checking for EPIPE error
  # use yes to accept all Android SDK licenses    
  - set +o pipefail
  - yes | /sdk/tools/bin/sdkmanager --licenses
  - set -o pipefail

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle/

variables:
  PROJECT_FOLDER: "Placeholder"

stages:
  - build

# Hidden Job
.build: &build_definition
  script:
  - export GRADLE_USER_HOME=`pwd`/Java/$PROJECT_FOLDER/.gradle
  - chmod +x ./Java/$PROJECT_FOLDER/gradlew
  - cd Java; cd $PROJECT_FOLDER; ./gradlew -Pci --console=plain :app:lintRelease
  - ./gradlew assembleRelease -PversionCode=${CI_JOB_ID}
  stage: build
  artifacts:
    paths:
    - Java/$PROJECT_FOLDER/app/build/reports
    - Java/$PROJECT_FOLDER/app/build/outputs/
  
DecodeListenerRelease:
  variables:
    PROJECT_FOLDER: "DecodeListener"
  <<: *build_definition
  
  
DecodeIntentRelease:
  variables:
    PROJECT_FOLDER: "DecodeIntent"
    <<: *build_definition


BarcodeScannerHTML5Release:
  variables:
    PROJECT_FOLDER: "BarcodeScannerHTML5"
    <<: *build_definition

CradleAppRelease:
  variables:
    PROJECT_FOLDER: "CradleApp"
    <<: *build_definition



# releaseTests:
#   stage: test
#   script:
#     - cd Java; cd DecodeListener; ./gradlew -Pci --console=plain :app:testRelease
#   artifacts:
#     paths:
#     - Java/DecodeListener/app/build/reports/tests/