image: javiersantos/android-ci:28.0.3

before_script:
  # temporarily disable checking for EPIPE error
  # use yes to accept all Android SDK licenses    
  - set +o pipefail
  - yes | /sdk/tools/bin/sdkmanager --licenses
  - set -o pipefail

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle/

stages:
  - build_A
  - build_B
  - build_C
  - build_D
  # - build_E
  # - build_F
  # - build_G
  # - test

# DecodeListener
DecodeListener:
  stage: build_A
  script:
    - export GRADLE_USER_HOME=`pwd`/Java/DecodeListener/.gradle
    - chmod +x ./Java/DecodeListener/gradlew
    - cd Java; cd DecodeListener; ./gradlew -Pci --console=plain :app:lintRelease
  artifacts:
    paths:
    - Java/DecodeListener/app/build/reports/
  script:
    - cd Java; cd DecodeListener; ./gradlew assembleRelease -PversionCode=${CI_JOB_ID}
  artifacts:
    paths:
    - Java/DecodeListener/app/build/outputs/

# DecodeIntent
lintDecodeIntent:
  stage: build_B
  script:
    - export GRADLE_USER_HOME=`pwd`/Java/DecodeIntent/.gradle
    - chmod +x ./Java/DecodeIntent/gradlew
    - cd Java; cd DecodeIntent; ./gradlew -Pci --console=plain :app:lintRelease
  artifacts:
    paths:
    - Java/DecodeIntent/app/build/reports/

assembleDecodeIntent:
  stage: build_B
  script:
    - export GRADLE_USER_HOME=`pwd`/Java/DecodeIntent/.gradle
    - chmod +x ./Java/DecodeIntent/gradlew
    - cd Java; cd DecodeIntent; ./gradlew assembleRelease -PversionCode=${CI_JOB_ID}
  artifacts:
    paths:
    - Java/DecodeIntent/app/build/outputs/

# BarcodeScannerHTML5
lintBarcodeHTML5:
  stage: build_C
  script:
    - export GRADLE_USER_HOME=`pwd`/Java/BarcodeScannerHTML5/.gradle
    - chmod +x ./Java/BarcodeScannerHTML5/gradlew
    - cd Java; cd BarcodeScannerHTML5; ./gradlew -Pci --console=plain :app:lintRelease
  artifacts:
    paths:
    - Java/BarcodeScannerHTML5/app/build/reports/

assembleBarcodeHTML5:
  stage: build_C
  script:
    - export GRADLE_USER_HOME=`pwd`/Java/BarcodeScannerHTML5/.gradle
    - chmod +x ./Java/BarcodeScannerHTML5/gradlew
    - cd Java; cd BarcodeScannerHTML5; ./gradlew assembleRelease -PversionCode=${CI_JOB_ID}
  artifacts:
    paths:
    - Java/BarcodeScannerHTML5/app/build/outputs/


# CradleApp
lintCradleApp:
  stage: build_D
  script:
    - export GRADLE_USER_HOME=`pwd`/Java/CradleApp/.gradle
    - chmod +x ./Java/CradleApp/gradlew
    - cd Java; cd CradleApp; ./gradlew -Pci --console=plain :app:lintRelease
  artifacts:
    paths:
    - Java/CradleApp/app/build/reports/

assembleCradleApp:
  stage: build_D
  script:
    - export GRADLE_USER_HOME=`pwd`/Java/CradleApp/.gradle
    - chmod +x ./Java/CradleApp/gradlew
    - cd Java; cd CradleApp; ./gradlew assembleRelease -PversionCode=${CI_JOB_ID}
  artifacts:
    paths:
    - Java/CradleApp/app/build/outputs/

# releaseTests:
#   stage: test
#   script:
#     - cd Java; cd DecodeListener; ./gradlew -Pci --console=plain :app:testRelease
#   artifacts:
#     paths:
#     - Java/DecodeListener/app/build/reports/tests/