image: javiersantos/android-ci:28.0.3

variables:
  # workaround self-signed certificate 
  GIT_SSL_NO_VERIFY: "1"

before_script:
  # temporarily disable checking for EPIPE error
  # use yes to accept all Android SDK licenses    
  - set +o pipefail
  - yes | /sdk/tools/bin/sdkmanager --licenses
  - set -o pipefail

  # setup gradle
  - export GRADLE_USER_HOME=`pwd`/Java/DecodeListener/.gradle
  - chmod +x ./Java/DecodeListener/gradlew


cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle/

stages:
  - build
  - test
  - deploy

lintRelease:
  stage: build
  script:
    - cd Java; cd DecodeListener; ./gradlew -Pci --console=plain :app:lintRelease
  artifacts:
    paths:
    - app/build/reports/

assembleRelease:
  stage: build
  script:
    - cd Java; cd DecodeListener; ./gradlew assembleRelease -PversionCode=${CI_JOB_ID}
  artifacts:
    paths:
    - app/build/outputs/

releaseTests:
  stage: test
  script:
    - cd Java; cd DecodeListener; ./gradlew -Pci --console=plain :app:testRelease
  artifacts:
    paths:
    - app/build/reports/tests/

deploy_staging:
 stage: deploy
 environment:
  name: staging
  url: https://github.com/lyonsja/Test_Deploy