image: javiersantos/android-ci:28.0.3

before_script:
  # temporarily disable checking for EPIPE error
  # use yes to accept all Android SDK licenses    
  - set +o pipefail
  - yes | /sdk/tools/bin/sdkmanager --licenses
  - set -o pipefail

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle/

variables:
  PROJECT_FOLDER: "DecodeListener"

stages:
  - build

# Hidden Job
.build: &build_definition
  script:
  - export GRADLE_USER_HOME=`pwd`/Java/$PROJECT_FOLDER/.gradle
  - chmod +x ./Java/$PROJECT_FOLDER/gradlew
  - cd Java; cd $PROJECT_FOLDER; ./gradlew -Pci --console=plain :app:lintRelease
  stage: build
  artifacts:
    paths:
    - Java/$PROJECT_FOLDER/app/build/reports
  
DecodeListenerRelease:
  script:
    export PROJECT_FOLDER="DecodeListener"
  <<: *build_definition
  
  
# # DecodeListener
# DecodeListener:
#   stage: build_A
#   script:
   
#   artifacts:
#     paths:
#     - Java/DecodeListener/app/build/reports/
#   script:
#     - cd Java; cd DecodeListener; ./gradlew assembleRelease -PversionCode=${CI_JOB_ID}
#   artifacts:
#     paths:
#     - Java/DecodeListener/app/build/outputs/

# # DecodeIntent
# lintDecodeIntent:
#   stage: build_B
#   script:
#     - export GRADLE_USER_HOME=`pwd`/Java/DecodeIntent/.gradle
#     - chmod +x ./Java/DecodeIntent/gradlew
#     - cd Java; cd DecodeIntent; ./gradlew -Pci --console=plain :app:lintRelease
#   artifacts:
#     paths:
#     - Java/DecodeIntent/app/build/reports/

# assembleDecodeIntent:
#   stage: build_B
#   script:
#     - export GRADLE_USER_HOME=`pwd`/Java/DecodeIntent/.gradle
#     - chmod +x ./Java/DecodeIntent/gradlew
#     - cd Java; cd DecodeIntent; ./gradlew assembleRelease -PversionCode=${CI_JOB_ID}
#   artifacts:
#     paths:
#     - Java/DecodeIntent/app/build/outputs/

# releaseTests:
#   stage: test
#   script:
#     - cd Java; cd DecodeListener; ./gradlew -Pci --console=plain :app:testRelease
#   artifacts:
#     paths:
#     - Java/DecodeListener/app/build/reports/tests/